language: python
before_install:
  - 'which ssh-agent || ( apt-get update && apt-get install -y openssh-client && apt install sshpass -y)'
  - mkdir -p .ssh
  - eval $(ssh-agent -s)
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > .ssh/config'
  - ssh-add <(echo "$SSH_Privatekey")
  - $SSH_Privatekey
  - composer install
  - composer dumpautoload -o
  - composer install --optimize-autoloader --no-dev
  - php artisan config:cache
  - php artisan vendor:publish --tag=ckeditor
script:
  - ssh -p22 -o StrictHostKeyChecking=no abdevp@abdevp.com 'rm -r /home/abdevp/abdevp_md/*'
  - scp -P22 -r ./* abdevp@abdevp.com:/home/abdevp/abdevp_md/
  - ssh -p22 -o StrictHostKeyChecking=no abdevp@abdevp.com 'ln -s ~/abdevp_md/storage/app/public ~/abdevp_md/public/storage'
