language: php
php: 
  - 7.2.10
sudo: enabled
cache: webblog.tar.gz
before_install:
  - sudo apt-get update
  - composer install
  - composer dumpautoload -o
  - composer install --optimize-autoloader --no-dev
  - php artisan config:cache
  - php artisan vendor:publish --tag=ckeditor
script:
  - cp .env.example .env
  - tar cvzf webblog.tar.gz *
